name: ci
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  as-lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"
      - name: Install dependencies
        run: npm install
      - name: Validate code is formatted
        run: npm run pretty:check
      - name: Validate code is linted
        run: npm run lint
      - name: Build the project
        run: npm run build
      - name: Publish GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: release.wasm
          path: functions/build/release.wasm
